name = "investment-blog-comments"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "blog-comments"
database_id = "9f737ab5-2f51-45bb-8892-62c156a99af8"

[vars]
ALLOWED_ORIGIN = "https://investment-blog-2lc.pages.dev"
